"""add payments table

Revision ID: 1850bcfb1aaa
Revises: cc92124320b9
Create Date: 2026-05-03 15:48:27.543053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1850bcfb1aaa'
down_revision: Union[str, None] = 'cc92124320b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_hash_id', sa.String(length=64), nullable=False),
    sa.Column('payer_id', sa.String(length=128), nullable=False, comment='User (Buyer) yang melakukan pembayaran'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False, comment='Contoh: DP, Termin 1, Pelunasan'),
    sa.Column('payment_receipt_url', sa.Text(), nullable=True, comment='URL gambar bukti transfer dari Firebase Storage'),
    sa.Column('sender_bank', sa.String(length=100), nullable=True, comment='Bank asal pembeli, misal: BCA, Mandiri'),
    sa.Column('sender_name', sa.String(length=255), nullable=True, comment='Nama pemilik rekening pengirim'),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=True, comment='pending, awaiting_verification, verified, rejected'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Alasan penolakan jika bukti transfer tidak valid'),
    sa.Column('verified_by', sa.String(length=128), nullable=True, comment='User (Petani) yang melakukan verifikasi'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu pembayaran disahkan oleh Petani'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_hash_id'], ['contracts.hash_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
