"""initial migration

Revision ID: 337d8b66ed37
Revises: 
Create Date: 2026-04-30 16:48:26.626064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '337d8b66ed37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Contoh: Forward Contract, Spot Contract'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_text_prompt', sa.Text(), nullable=False, comment='Instruksi dasar legal untuk Gemini AI'),
    sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Definisi input form dinamis di frontend'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_templates_id'), 'contract_templates', ['id'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.String(length=100), nullable=False, comment='Contoh: cabe_rawit_merah'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False, comment='Firebase UID'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False, comment='farmer atau buyer'),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_province', sa.String(length=100), nullable=True),
    sa.Column('address_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('commodities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_farmer_id'), 'commodities', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_commodities_id'), 'commodities', ['id'], unique=False)
    op.create_table('market_price_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_price_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Integer(), nullable=False),
    sa.Column('previous_price', sa.Integer(), nullable=False),
    sa.Column('change_rp', sa.Integer(), nullable=False),
    sa.Column('change_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=True, comment='up, down, stable'),
    sa.ForeignKeyConstraint(['market_price_id'], ['market_prices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_price_daily_id'), 'market_price_daily', ['id'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quality_grade', sa.String(length=100), nullable=True, comment='Contoh: Grade A Premium'),
    sa.Column('payment_method', sa.String(length=100), nullable=True, comment='Contoh: Transfer Bank, Escrow'),
    sa.Column('payment_term', sa.String(length=100), nullable=True, comment='Contoh: DP 30%, CBD, Termin 14 Hari'),
    sa.Column('shipping_point', sa.String(length=255), nullable=True, comment='Contoh: Loco Gudang Petani, Franko Pabrik'),
    sa.Column('delivery_type', sa.String(length=100), nullable=True, comment='Contoh: Sekaligus (Full), Bertahap (Parsial)'),
    sa.Column('proposed_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='negotiating', nullable=True, comment='negotiating, accepted, rejected'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiations_buyer_id'), 'negotiations', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_negotiations_farmer_id'), 'negotiations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_negotiations_id'), 'negotiations', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('hash_id', sa.String(length=64), nullable=False, comment='SHA-256 Hash Utama'),
    sa.Column('negotiation_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_agreed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quality_grade', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('payment_term', sa.String(length=100), nullable=False),
    sa.Column('shipping_point', sa.String(length=255), nullable=False),
    sa.Column('delivery_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=True, comment='pending, partially_fulfilled, completed'),
    sa.Column('mou_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('negotiation_id')
    )
    op.create_table('negotiation_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('negotiation_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quality_grade', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('payment_term', sa.String(length=100), nullable=True),
    sa.Column('shipping_point', sa.String(length=255), nullable=True),
    sa.Column('delivery_type', sa.String(length=100), nullable=True),
    sa.Column('proposed_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_histories_id'), 'negotiation_histories', ['id'], unique=False)
    op.create_table('fulfillments',
    sa.Column('hash_id', sa.String(length=64), nullable=False, comment='SHA-256 Hash Pengiriman'),
    sa.Column('contract_hash_id', sa.String(length=64), nullable=False),
    sa.Column('delivery_volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='in_transit', nullable=True, comment='in_transit, received, rejected'),
    sa.Column('buyer_notes', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_hash_id'], ['contracts.hash_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('hash_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fulfillments')
    op.drop_index(op.f('ix_negotiation_histories_id'), table_name='negotiation_histories')
    op.drop_table('negotiation_histories')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_negotiations_id'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_farmer_id'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_buyer_id'), table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_market_price_daily_id'), table_name='market_price_daily')
    op.drop_table('market_price_daily')
    op.drop_index(op.f('ix_commodities_id'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_farmer_id'), table_name='commodities')
    op.drop_table('commodities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_contract_templates_id'), table_name='contract_templates')
    op.drop_table('contract_templates')
    # ### end Alembic commands ###
