"""adding province city village sawah

Revision ID: 4101a5a4f49f
Revises: fd04fc218b54
Create Date: 2026-05-03 15:01:27.335952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4101a5a4f49f'
down_revision: Union[str, None] = 'fd04fc218b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinsi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provinsi_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provinsi_id'), 'provinsi', ['id'], unique=False)
    op.create_table('kota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provinsi_id', sa.Integer(), nullable=False),
    sa.Column('kota_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kota_id'), 'kota', ['id'], unique=False)
    op.create_table('kecamatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kota_id', sa.Integer(), nullable=False),
    sa.Column('kecamatan_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['kota_id'], ['kota.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kecamatan_id'), 'kecamatan', ['id'], unique=False)
    op.create_table('sawah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.String(length=128), nullable=False),
    sa.Column('id_provinsi', sa.Integer(), nullable=False),
    sa.Column('id_kota', sa.Integer(), nullable=False),
    sa.Column('id_kecamatan', sa.Integer(), nullable=False),
    sa.Column('luas_sawah', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('address_detail', sa.Text(), nullable=True),
    sa.Column('kondisi_tanah', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_kecamatan'], ['kecamatan.id'], ),
    sa.ForeignKeyConstraint(['id_kota'], ['kota.id'], ),
    sa.ForeignKeyConstraint(['id_provinsi'], ['provinsi.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sawah_id'), 'sawah', ['id'], unique=False)
    op.add_column('commodities', sa.Column('path_image', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('id_provinsi', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('id_kota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('id_kecamatan', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'provinsi', ['id_provinsi'], ['id'])
    op.create_foreign_key(None, 'users', 'kecamatan', ['id_kecamatan'], ['id'])
    op.create_foreign_key(None, 'users', 'kota', ['id_kota'], ['id'])
    op.drop_column('users', 'address_city')
    op.drop_column('users', 'address_province')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_province', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'id_kecamatan')
    op.drop_column('users', 'id_kota')
    op.drop_column('users', 'id_provinsi')
    op.drop_column('commodities', 'path_image')
    op.drop_index(op.f('ix_sawah_id'), table_name='sawah')
    op.drop_table('sawah')
    op.drop_index(op.f('ix_kecamatan_id'), table_name='kecamatan')
    op.drop_table('kecamatan')
    op.drop_index(op.f('ix_kota_id'), table_name='kota')
    op.drop_table('kota')
    op.drop_index(op.f('ix_provinsi_id'), table_name='provinsi')
    op.drop_table('provinsi')
    # ### end Alembic commands ###
