"""refactor negotiation lookup tables

Revision ID: cc92124320b9
Revises: 4101a5a4f49f
Create Date: 2026-05-03 15:44:43.230525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc92124320b9'
down_revision: Union[str, None] = '4101a5a4f49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False, comment='Contoh: Sekaligus (Full), Bertahap (Parsial)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_type_id'), 'delivery_type', ['id'], unique=False)
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_method_id'), 'payment_method', ['id'], unique=False)
    op.create_table('payment_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False, comment='Contoh: DP 30%, CBD, Termin 14 Hari'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_term_id'), 'payment_term', ['id'], unique=False)
    op.create_table('quality_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False, comment='Contoh: Grade A Premium'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_grade_id'), 'quality_grade', ['id'], unique=False)
    op.create_table('shipping_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False, comment='Contoh: Loco Gudang Petani, Franko Pabrik'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_point_id'), 'shipping_point', ['id'], unique=False)
    op.add_column('negotiation_histories', sa.Column('quality_grade_id', sa.Integer(), nullable=True))
    op.add_column('negotiation_histories', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.add_column('negotiation_histories', sa.Column('payment_term_id', sa.Integer(), nullable=True))
    op.add_column('negotiation_histories', sa.Column('shipping_point_id', sa.Integer(), nullable=True))
    op.add_column('negotiation_histories', sa.Column('delivery_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'negotiation_histories', 'payment_term', ['payment_term_id'], ['id'])
    op.create_foreign_key(None, 'negotiation_histories', 'payment_method', ['payment_method_id'], ['id'])
    op.create_foreign_key(None, 'negotiation_histories', 'quality_grade', ['quality_grade_id'], ['id'])
    op.create_foreign_key(None, 'negotiation_histories', 'shipping_point', ['shipping_point_id'], ['id'])
    op.create_foreign_key(None, 'negotiation_histories', 'delivery_type', ['delivery_type_id'], ['id'])
    op.drop_column('negotiation_histories', 'payment_method')
    op.drop_column('negotiation_histories', 'quality_grade')
    op.drop_column('negotiation_histories', 'shipping_point')
    op.drop_column('negotiation_histories', 'payment_term')
    op.drop_column('negotiation_histories', 'delivery_type')
    op.add_column('negotiations', sa.Column('quality_grade_id', sa.Integer(), nullable=True))
    op.add_column('negotiations', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.add_column('negotiations', sa.Column('payment_term_id', sa.Integer(), nullable=True))
    op.add_column('negotiations', sa.Column('shipping_point_id', sa.Integer(), nullable=True))
    op.add_column('negotiations', sa.Column('delivery_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('negotiations_template_id_fkey', 'negotiations', type_='foreignkey')
    op.create_foreign_key(None, 'negotiations', 'payment_term', ['payment_term_id'], ['id'])
    op.create_foreign_key(None, 'negotiations', 'shipping_point', ['shipping_point_id'], ['id'])
    op.create_foreign_key(None, 'negotiations', 'quality_grade', ['quality_grade_id'], ['id'])
    op.create_foreign_key(None, 'negotiations', 'delivery_type', ['delivery_type_id'], ['id'])
    op.create_foreign_key(None, 'negotiations', 'payment_method', ['payment_method_id'], ['id'])
    op.drop_column('negotiations', 'payment_method')
    op.drop_column('negotiations', 'quality_grade')
    op.drop_column('negotiations', 'shipping_point')
    op.drop_column('negotiations', 'payment_term')
    op.drop_column('negotiations', 'template_id')
    op.drop_column('negotiations', 'delivery_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negotiations', sa.Column('delivery_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Contoh: Sekaligus (Full), Bertahap (Parsial)'))
    op.add_column('negotiations', sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('negotiations', sa.Column('payment_term', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Contoh: DP 30%, CBD, Termin 14 Hari'))
    op.add_column('negotiations', sa.Column('shipping_point', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Contoh: Loco Gudang Petani, Franko Pabrik'))
    op.add_column('negotiations', sa.Column('quality_grade', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Contoh: Grade A Premium'))
    op.add_column('negotiations', sa.Column('payment_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Contoh: Transfer Bank, Escrow'))
    op.drop_constraint(None, 'negotiations', type_='foreignkey')
    op.drop_constraint(None, 'negotiations', type_='foreignkey')
    op.drop_constraint(None, 'negotiations', type_='foreignkey')
    op.drop_constraint(None, 'negotiations', type_='foreignkey')
    op.drop_constraint(None, 'negotiations', type_='foreignkey')
    op.create_foreign_key('negotiations_template_id_fkey', 'negotiations', 'contract_templates', ['template_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('negotiations', 'delivery_type_id')
    op.drop_column('negotiations', 'shipping_point_id')
    op.drop_column('negotiations', 'payment_term_id')
    op.drop_column('negotiations', 'payment_method_id')
    op.drop_column('negotiations', 'quality_grade_id')
    op.add_column('negotiation_histories', sa.Column('delivery_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('negotiation_histories', sa.Column('payment_term', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('negotiation_histories', sa.Column('shipping_point', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('negotiation_histories', sa.Column('quality_grade', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('negotiation_histories', sa.Column('payment_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'negotiation_histories', type_='foreignkey')
    op.drop_constraint(None, 'negotiation_histories', type_='foreignkey')
    op.drop_constraint(None, 'negotiation_histories', type_='foreignkey')
    op.drop_constraint(None, 'negotiation_histories', type_='foreignkey')
    op.drop_constraint(None, 'negotiation_histories', type_='foreignkey')
    op.drop_column('negotiation_histories', 'delivery_type_id')
    op.drop_column('negotiation_histories', 'shipping_point_id')
    op.drop_column('negotiation_histories', 'payment_term_id')
    op.drop_column('negotiation_histories', 'payment_method_id')
    op.drop_column('negotiation_histories', 'quality_grade_id')
    op.drop_index(op.f('ix_shipping_point_id'), table_name='shipping_point')
    op.drop_table('shipping_point')
    op.drop_index(op.f('ix_quality_grade_id'), table_name='quality_grade')
    op.drop_table('quality_grade')
    op.drop_index(op.f('ix_payment_term_id'), table_name='payment_term')
    op.drop_table('payment_term')
    op.drop_index(op.f('ix_payment_method_id'), table_name='payment_method')
    op.drop_table('payment_method')
    op.drop_index(op.f('ix_delivery_type_id'), table_name='delivery_type')
    op.drop_table('delivery_type')
    # ### end Alembic commands ###
