"""nama_perubahan_kamu

Revision ID: fd04fc218b54
Revises: 337d8b66ed37
Create Date: 2026-04-30 16:50:05.748797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd04fc218b54'
down_revision: Union[str, None] = '337d8b66ed37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
